### ISSUE TITLE
pip install old not working version of the software (version installed 0.7.3)

### ISSUE THREAD

**Issue by pierlui92** [galeone/dynamic-training-bench#21]
System information
TensorFlow version: 1.5
Python version: 3.5
CUDA/cuDNN version: CUDA 9.0, CuDNN 7

Command to reproduce:
Install dytb through pip
import dytb

Error:

```
Traceback (most recent call last):
File "CNNANGLESPECIFIC.py", line 14, in <module>
   from dytb.models.utils import variables_to_restore
   File "/home/pier/piervenv/local/lib/python3.5/site-packages/dytb/models/utils.py", line 12, in <module>>     from .collections import MODEL_SUMMARIES, REQUIRED_NON_TRAINABLES
 ImportError: cannot import name 'MODEL_SUMMARIES'
```

**Comment by galeone** [comment]
Thank you for reporting this: fixed. (It was some strange cache issues when building the wheel)
